### ISSUE TITLE
#랜덤 레이드 결과 값 대체

### ISSUE THREAD

**Issue by Adihang** [nOctaveLay/Destiny-Bot#1]
raid_list = [
'수호자, 몇 초 지체하면 모두가 폭4하는 별의탑 고급은 어떠신가요?',
'버그가 난무하는 마지막소원도 재미있을것 같아요.',
'선잇기놀이가 재미있는 구원의 정원을 추천해요.',
'레이드 입문으로 괜찮은 행성포식자가 좋을 것 같아요.',
'레이드를 여러번 하는 느낌을 즐길 수 있는 리바이어던이 재미있어요.',
'수호자, 가볍게 20분만에 할 수 있는 과거의 고통을 해보시는게 어떨까요?',
'디버프 폭탄돌리기 메커니즘이 재미있는 슬픔의 왕관이 재미있어요'
]

**Comment by nOctaveLay** [comment]
---> print_raid update. it is revised
